# -*- coding: utf-8 -*-
"""Техношкола_ВБ.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kRY9ud0UI8M5ErB4JH2VDQl3lfLbnnX3
"""

import kagglehub
import shutil
import os
import pandas as pd

# Скачиваем датасет
dataset_dir = kagglehub.dataset_download("iamsouravbanerjee/customer-shopping-trends-dataset")

# Копируем в рабочую директорию Colab
destination = "/content/"
os.makedirs(destination, exist_ok=True)

# Iterate through files within the downloaded dataset directory
for filename in os.listdir(dataset_dir):
    file_path = os.path.join(dataset_dir, filename)
    # Check if it's a file before copying
    if os.path.isfile(file_path):
        shutil.copy2(file_path, destination)

df = pd.read_csv('/content/shopping_trends.csv')

df

"""#1.1"""

# Гипотеза 1: Старшие клиенты (старше 40 лет) предпочитают большие размеры
df['Age Group'] = pd.cut(df['Age'], bins=[0, 40, 100], labels=["40 and below", "Above 40"])
size_age_crosstab = pd.crosstab(df['Size'], df['Age Group'])
size_age_crosstab_prop = size_age_crosstab.div(size_age_crosstab.sum(axis=0), axis=1)
print(size_age_crosstab_prop)

"""Не подтвердилось

"""

# Гипотеза 2: Покупатели, использующие скидки, покупают более дорогие товары
discount_spending = df.groupby('Discount Applied')['Purchase Amount (USD)'].mean()
print(discount_spending)

"""Не подтвердилось"""

# Гипотеза 3: Женщины покупают более яркие вещи
gender_color_crosstab = pd.crosstab(df['Gender'], df['Color'])
print(gender_color_crosstab)

"""Не подтвердилось т.к. мужчин в 2 раза больше"""

# Гипотеза 4: Частота покупок влияет на среднюю сумму
freq_spending = df.groupby('Frequency of Purchases')['Purchase Amount (USD)'].mean()
print(freq_spending)

"""Не подтвердилось"""

# Гипотеза 5: Наличие подписки связано с количеством предыдущих покупок
subs_prev_purchases = df.groupby('Subscription Status')['Previous Purchases'].mean()
print(subs_prev_purchases)

"""Не подтвердилось

#1.2
###Помимо гипотез:
####-найдите самый популярный товар
####-постройте распределение покупателей по полу
####-определите, какой пол (и отдельно возраст) покупает больше всего, чаще всего, самые дорогие товары
####-определите, есть ли зависимость между цветом одежды и сезоном.
####-посчитайте наш сезонный mau (уникальных пользователей за сезон) и его динамику.
####-найдите самую популярную букву в названии одежды.
"""

print(f"Cамый популярный товар: {df['Item Purchased'].value_counts().idxmax()} ({df['Item Purchased'].value_counts().max()})")

gender_distribution = df['Gender'].value_counts()
print("Распределение покупателей по полу:")
print(gender_distribution)

# По количеству
most_buyers_gender = df.groupby('Gender').size().idxmax()
most_buyers_age = df.groupby('Age')['Purchase Amount (USD)'].sum().idxmax()

# По средней стоимости
most_expensive_gender = df.groupby('Gender')['Purchase Amount (USD)'].mean().idxmax()
most_expensive_age = df.groupby('Age')['Purchase Amount (USD)'].mean().idxmax()

print(f"Больше всего покупают: {most_buyers_gender} и возраст {most_buyers_age}")
print(f"Самые дорогие покупки совершают: {most_expensive_gender} и возраст {most_expensive_age}")

color_season_crosstab = pd.crosstab(df['Color'], df['Season'])
print("Зависимость между цветом одежды и сезоном:")
print(color_season_crosstab)

"""Очень странная зависимость. Весной почему-то покупают Оливковые вещи, хотя вроде надо готовиться к лету. Осенью покупают желтые и розовые вещи. Но возможно это связано связано с типом товара. Может быть это губная помада или яркий аксессуар."""

season_mau = df.groupby('Season')['Customer ID'].nunique()
print("Сезонный MAU:")
print(season_mau)

"""Возможно весной больше покупают, т.к. будет подготовка к лету"""

clothing_items = df[df['Category'] == 'Clothing']['Item Purchased']

clothing_letters = ''.join(clothing_items.dropna())

from collections import Counter
clothing_letter_counts = Counter(clothing_letters.replace(' ', '').lower())

most_popular_clothing_letter = max(clothing_letter_counts, key=clothing_letter_counts.get)

print(f"Самая популярная буква в названиях товаров категории 'Clothing': {most_popular_clothing_letter}")